version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8'
    steps:
      - 'checkout'
      - restore_cache:
          key: 'node-cache-{{ checksum "package-lock.json" }}'
      - run: 'npm ci'
      - save_cache:
          key: 'node-cache-{{ checksum "package-lock.json" }}'
          paths:
            - 'node_modules'
      - run: 'npm run ci'
